
path: D:/coding-project/foodify/data # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: Bawang merah
  1: Bawang putih
  2: Cabai hijau
  3: Cabai merah
