
path: /content/gdrive/My Drive/Foodify/data #dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: Bawang merah
  1: Bawang putih
